{
 "title": "Shard2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Colony", "query": "stats.gauges.shard2.colonies.*" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.shard2.cpu.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.shard2.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(stats.gauges.shard2.cpu.limit, 'Limit')"
    },
    {
     "target": "alias(movingAverage(stats.gauges.shard2.cpu.used, '1hour'), 'Used 1h avg')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.shard2.cpu.bucket" }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(stats.gauges.shard2.time), 'Ticks Per Update')"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.shard2.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(stats.gauges.shard2.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.shard2.gcl.progressTotal, #B), #C)"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.shard2.gcl.progress), #B), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.shard2.gcl.progress), #B), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Creeps by Role",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shard2.creeps.*, 3)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shard2.resources.*, 3)"
    },
    {
     "target": "aliasByNode(stats.gauges.shard2.credits, 2)"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.shard2.kingdomCpu)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.scheduler.processCpu.*)"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.shard2.scheduler.numProcesses)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.scheduler.ranOutOfTime)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.scheduler.timeLimit)"
    },
    {
     "target": "alias(nonNegativeDerivative(stats.gauges.shard2.scheduler.ranOutOfTime, 0), 'skipped')"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.shard2.topics.*, 3)"
    }
   ]
  },
  {
   "title": "Path Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.shard2.path_cache.listCount)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.path_cache.cacheHits)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.path_cache.cacheMisses)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.path_cache.roomCacheSize)"
    },
    {
     "target": "aliasByMetric(stats.gauges.shard2.path_cache.size)"
    }
   ]
  },
  {
   "title": "$Colony",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "Colony",
   "collapsed": true,
   "panels": [
    {
     "title": "RCL",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "maxSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerLevel)"
      }
     ]
    },
    {
     "title": "Time to Next RCL",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 43 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "target": "divideSeries(diffSeries(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
       "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
      }
     ]
    },
    {
     "title": "RCL Upgrade",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
       "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.shard2.time)), 'GCL per tick')"
      },
      {
       "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
       "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.shard2.time)), '1hour'), '1hr Moving Average')"
      }
     ]
    },
    {
     "title": "Stored Energy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "refCount": -1,
       "target": "alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
      },
      {
       "refCount": -1,
       "target": "alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
      },
      {
       "refCount": -1,
       "target": "alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
      },
      {
       "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
       "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.shard2.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
      }
     ]
    },
    {
     "title": "Topic Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.topics.*, 5)"
      }
     ]
    },
    {
     "title": "Energy left in source",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
      }
     ]
    },
    {
     "title": "Logistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.desiredHaulers, 4)"
      },
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.pidDesiredHaulers, 4)"
      },
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.haulTasks, 4)"
      },
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.numHaulers, 4)"
      },
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.haulerSetpoint, 4)"
      },
      {
       "target": "alias(movingAverage(stats.gauges.shard2.colonies.$Colony.pidDesiredHaulers, '30min'), 'desired 30m avg')"
      }
     ]
    },
    {
     "title": "Source Container Free Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
      }
     ]
    },
    {
     "title": "Spawning & Boost Prep",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.booster.*, 5)"
      },
      {
       "target": "aliasByNode(stats.gauges.shard2.colonies.$Colony.spawner.*.isSpawning, 6)"
      }
     ]
    },
    {
     "title": "Room Resources",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(stats.gauges.shard2.colonies.$Colony.rooms.*.resources.*)"
      }
     ]
    }
   ]
  }
 ]
}