apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: graphite-data
  name: graphite-data
  namespace: screeps
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "openebs-sc-screeps-graphite-data"
  resources:
    requests:
      storage: 50Gi
status: {}
