apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: graphite
  name: graphite
  namespace: screeps
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "2003"
    port: 2003
    targetPort: 2003
    protocol: TCP
  selector:
    io.kompose.service: graphite
