apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: graphite-claim0
  name: graphite-claim0
  namespace: screeps
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "openebs-sc-screeps-graphite-config"
  resources:
    requests:
      storage: 100Mi
status: {}
